import React, { useState, useEffect } from 'react';
import { brainGateway } from '@/coreos/brain/gateway';
import { BrainRequest } from '@/coreos/brain/types';

interface AIExplanationPanelProps {
    appId: string;
    contextParams: Record<string, any>; // e.g., { permission: 'fs.write', risk: 'DANGEROUS' }
    prompt: string; // "Explain why fs.write is dangerous"
    title?: string;
    onClose?: () => void;
}

export function AIExplanationPanel({ appId, contextParams, prompt, title = 'AI Insight', onClose }: AIExplanationPanelProps) {
    const [explanation, setExplanation] = useState<string | null>(null);
    const [loading, setLoading] = useState(false);
    const [error, setError] = useState<string | null>(null);
    const [feedback, setFeedback] = useState<'useful' | 'not_useful' | null>(null);

    useEffect(() => {
        let isMounted = true;

        async function fetchExplanation() {
            setLoading(true);
            try {
                // Construct Shadow Request
                const req: BrainRequest = {
                    appId,
                    correlationId: `shadow-${Date.now()}`,
                    messages: [
                        { role: 'user', content: prompt }
                    ],
                    userId: 'user', // Current User
                    context: contextParams,
                    shadow: true // 🌑 Shadow Mode
                };

                const res = await brainGateway.processRequest(req);
                if (isMounted) {
                    setExplanation(res.content || 'No explanation provided.');
                }
            } catch (err: any) {
                if (isMounted) {
                    setError('Unable to load explanation.');
                    console.error(err);
                }
            } finally {
                if (isMounted) setLoading(false);
            }
        }

        fetchExplanation();

        return () => { isMounted = false; };
    }, [prompt, appId]); // Re-fetch if prompt changes

    const handleFeedback = (type: 'useful' | 'not_useful') => {
        setFeedback(type);
        // Telemetry would go here (brain.shadow_used / ignored)
        console.log(`[Feedback] ${type}`);
    };

    if (error) return null; // Fail gracefully (Shadow shouldn't break UI)

    return (
        <div style={styles.container}>
            <div style={styles.header}>
                <span style={styles.icon}>✨</span>
                <span style={styles.title}>{title}</span>
                {onClose && <button onClick={onClose} style={styles.closeBtn}>×</button>}
            </div>

            <div style={styles.content}>
                {loading ? (
                    <span style={styles.loading}>Analyzing...</span>
                ) : (
                    <p style={styles.text}>{explanation}</p>
                )}
            </div>

            {!loading && explanation && (
                <div style={styles.footer}>
                    <span style={styles.disclaimer}>Generated by AI • Observer Mode</span>
                    {!feedback ? (
                        <div style={styles.actions}>
                            <button onClick={() => handleFeedback('useful')} style={styles.actionBtn}>👍</button>
                            <button onClick={() => handleFeedback('not_useful')} style={styles.actionBtn}>👎</button>
                        </div>
                    ) : (
                        <span style={styles.thanks}>Thanks for feedback!</span>
                    )}
                </div>
            )}
        </div>
    );
}

const styles: Record<string, React.CSSProperties> = {
    container: {
        background: 'rgba(255, 255, 255, 0.05)',
        border: '1px solid rgba(255, 255, 255, 0.1)',
        borderRadius: 8,
        padding: 12,
        marginTop: 10,
        fontSize: 13,
        color: '#e5e5e5',
        backdropFilter: 'blur(10px)',
    },
    header: {
        display: 'flex',
        alignItems: 'center',
        gap: 6,
        marginBottom: 8,
        fontWeight: 600,
        color: '#a855f7', // Purple for AI
    },
    icon: { fontSize: 14 },
    title: { flex: 1 },
    closeBtn: {
        background: 'none',
        border: 'none',
        color: '#666',
        cursor: 'pointer',
        fontSize: 16,
    },
    content: {
        lineHeight: 1.5,
        opacity: 0.9,
    },
    loading: {
        fontStyle: 'italic',
        opacity: 0.6,
        fontSize: 12,
    },
    text: { margin: 0 },
    footer: {
        marginTop: 10,
        paddingTop: 8,
        borderTop: '1px solid rgba(255, 255, 255, 0.05)',
        display: 'flex',
        justifyContent: 'space-between',
        alignItems: 'center',
        fontSize: 11,
    },
    disclaimer: {
        opacity: 0.5,
    },
    actions: {
        display: 'flex',
        gap: 4,
    },
    actionBtn: {
        background: 'none',
        border: 'none',
        cursor: 'pointer',
        opacity: 0.6,
        transition: 'opacity 0.2s',
        padding: '0 4px',
    },
    thanks: {
        color: '#22c55e',
        fontWeight: 500,
    }
};
